dist: trusty
language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  # Ensure PIP is up-to-date to avoid warnings.
  - python -m pip install --upgrade pip

  # modify ImageMagick policy file so that Textclips work correctly.
  # `| sudo tee` replaces `>` so that it can have root permissions
  - cat /etc/ImageMagick/policy.xml | sed 's/none/read,write/g' | sudo tee /etc/ImageMagick/policy.xml


install:
  - pip install tox-travis
  - pip install flake8

script:
  - tox
  - coverage run --source icon_font_to_png -m py.test
  - coverage report -m

  # - python setup.py test --pytest-args "tests/ --doctest-modules -v --cov moviepy --cov-report term-missing"
  # Now the *code* is tested, let's check that the setup is compatible with PIP without falling over.
  - pip install -e .
  - pip install -e .[optional]
  - pip install -e .[test]
  # Only test doc generation on latest. Doesn't work on some earlier versions (3.3), but doesn't matter.
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install -e .[doc]; fi

after_success:
  - coveralls